ClusterName=microchip-eda-lab
SlurmctldHost=slurmctld
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
AuthType=auth/munge
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldPort=6817
SlurmdPort=6818
SlurmdParameters=config_overrides
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
JobAcctGatherType=jobacct_gather/linux
JobCompType=jobcomp/none
TaskPlugin=task/none
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=120
DefMemPerCPU=512
MaxMemPerCPU=4096
Licenses=cadence:1,synopsys:1,siemens:1

NodeName=compute1 CPUs=2 RealMemory=2048 State=UNKNOWN
NodeName=compute2 CPUs=2 RealMemory=2048 State=UNKNOWN

PartitionName=eda Nodes=compute[1-2] Default=YES MaxTime=02:00:00 State=UP OverSubscribe=NO
PartitionName=debug Nodes=compute[1-2] MaxTime=00:30:00 State=UP OverSubscribe=YES
PartitionName=long Nodes=compute[1-2] MaxTime=08:00:00 State=UP OverSubscribe=NO
